<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '3418cc1dc849110670200cb20735cb9b8747b34a',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '3418cc1dc849110670200cb20735cb9b8747b34a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bacon/bacon-qr-code' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => '510de6eca6248d77d31b339d62437cc995e2fb41',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => '6faf451159fb8ba4126b925ed2d78acfce0dc016',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '5.0.9',
            'version' => '5.0.9.0',
            'reference' => '3dcdfab4c9122874f3915d8bf80a43b9df11852d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'khanamiryan/qrcode-detector-decoder' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '8d53cbecaa32f1e56a3be58bb3055ac31774ecd0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../khanamiryan/qrcode-detector-decoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'picqer/php-barcode-generator' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'reference' => '4cec18909dffd86e14beb69b1040f2520c2e1bb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../picqer/php-barcode-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
